### ISSUE TITLE
Can't APT UPDATE?

### ISSUE THREAD

**Issue by framistat** [ntguest/32bit-home-assistant-supervised-installer#1]
Getting errors...  by the way, following the link, this image downloaded from chuangtzu.ftp.acc.umu.se and it took forever from USA.

user1@D610:~$ su -
Password: 
root@D610:~# apt update
Ign:1 cdrom://[Debian GNU/Linux 11.1.0 _Bullseye_ - Unofficial i386 DVD Binary-1 with firmware 20211009-10:15] bullseye InRelease
Err:2 cdrom://[Debian GNU/Linux 11.1.0 _Bullseye_ - Unofficial i386 DVD Binary-1 with firmware 20211009-10:15] bullseye Release
  Please use apt-cdrom to make this CD-ROM recognized by APT. apt-get update cannot be used to add new CD-ROMs
Hit:3 http://deb.debian.org/debian bullseye InRelease
Hit:4 http://security.debian.org/debian-security bullseye-security InRelease
Hit:5 http://deb.debian.org/debian bullseye-updates InRelease
Reading package lists... Done
E: The repository 'cdrom://[Debian GNU/Linux 11.1.0 _Bullseye_ - Unofficial i386 DVD Binary-1 with firmware 20211009-10:15] bullseye Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@D610:~#

**Comment by ntguest** [comment]
When you install Debian 11 using a DVD, the OS installer sets the DVD as the source for getting packages for your system if you didn’t choose to scan for network mirrors.
Due to this reason, the system would ask you to insert a DVD if the disc is not present in the DVD drive when you try to install any software.  Also, the packages on DVD may not be the latest release.  So, we need to get the packages from the Internet.

just commit out the cd-rom stuff from your source.list

`nano /etc/apt/sources.list
`
